<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Thank you. Your order has been received</name>
   <tag></tag>
   <elementGuidId>c7cb49a2-2d5b-442f-a5e7-46ec55bd53d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-notice.woocommerce-notice--success.woocommerce-thankyou-order-received</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-9']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>000df5d8-455c-425e-a233-323edfdbfb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-notice woocommerce-notice--success woocommerce-thankyou-order-received</value>
      <webElementGuid>0b7a2af4-777d-4fce-bfc0-ccf12a8975d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you. Your order has been received.</value>
      <webElementGuid>ad343ed2-d790-4c61-8ae5-b8f66577447a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-9&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-order&quot;]/p[@class=&quot;woocommerce-notice woocommerce-notice--success woocommerce-thankyou-order-received&quot;]</value>
      <webElementGuid>05cdf47d-ea65-4da6-bbd0-7e1fd3b77bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-9']/div/div/div/p</value>
      <webElementGuid>723323d5-1c6b-4b92-8374-bff4b8039017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[3]/following::p[1]</value>
      <webElementGuid>28f934cd-830f-4502-b125-3eb36167ce29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/following::p[1]</value>
      <webElementGuid>6d0e331e-b819-4c69-b258-3d6cbba99271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you. Your order has been received.']/parent::*</value>
      <webElementGuid>dff290d0-095d-421d-aaad-3b6b8a374cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>ded092c1-21b2-4813-9433-2d8d100b4f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Thank you. Your order has been received.' or . = 'Thank you. Your order has been received.')]</value>
      <webElementGuid>00dfc8a2-f845-4f6a-a041-e07901a39aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
