<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search_ellie-icon-search</name>
   <tag></tag>
   <elementGuidId>c6aaa83e-33c9-49fa-b1f5-dd2590f2c76d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ellie-icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='search-2']/form/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cb2266c9-f3b4-4801-b1ac-88c4a1d93fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellie-icon-search</value>
      <webElementGuid>445385ca-5b69-4222-885f-8405e9384c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-2&quot;)/form[@class=&quot;search-form&quot;]/button[@class=&quot;search-submit&quot;]/i[@class=&quot;ellie-icon-search&quot;]</value>
      <webElementGuid>67fb0df4-f854-4bb0-9f73-0dae1548c2fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='search-2']/form/button/i</value>
      <webElementGuid>04c713be-7c2b-4455-b1fd-fc5199b912dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>d1bd9cf3-36bd-4a0d-863b-a19283f7288c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
