<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Katalon Training Day 2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cefbe42b-49ec-4f06-ac96-c554c2f939c4</testSuiteGuid>
   <testCaseLink>
      <guid>029f8ab2-fe5c-4b7b-9938-aaf63ec080b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Training Day 2/TC 01 - Login Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51900455-61c6-4da6-9b96-bd08cd9c28a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb823344-fff7-440e-9dc2-7c67a1b62a3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66bfe28c-0324-4963-91cc-38fba3ba5f34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Training Day 2/TC 02 - Search Funtionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51900455-61c6-4da6-9b96-bd08cd9c28a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb823344-fff7-440e-9dc2-7c67a1b62a3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>546bb8cc-f2ab-4ee2-8ecc-b5ceb43cde07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c86fddfa-3d66-4950-bba0-35895738067e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Training Day 2/TC 03 - Add to Cart Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51900455-61c6-4da6-9b96-bd08cd9c28a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb823344-fff7-440e-9dc2-7c67a1b62a3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3baa77f8-955e-472f-952b-7200d00b20bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Training Day 2/TC 04 - Checkout Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
