<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test</name>
   <tag></tag>
   <elementGuidId>6ceb6693-9ed4-4ad3-b297-badec0f00d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tsuid_24']/span/div/div/div[3]/div/div/div[2]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.JgzqYd.RES9jf.xWMiCc > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f2b223a-2945-42e3-9b2c-ac4f08736862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dobid</name>
      <type>Main</type>
      <value>hdw</value>
      <webElementGuid>66576b9f-7f8f-420e-9c52-c6c288f8aaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>4a88e259-a86b-4798-b316-29227ff20b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsuid_24&quot;)/span[1]/div[1]/div[@class=&quot;lr_container yc7KLc mBNN3d&quot;]/div[3]/div[@class=&quot;VpH2eb vmod&quot;]/div[@class=&quot;gBoaXb sxr04b&quot;]/div[@class=&quot;kVF6d&quot;]/div[@class=&quot;MiCl6d&quot;]/div[@class=&quot;JgzqYd RES9jf xWMiCc&quot;]/span[1]</value>
      <webElementGuid>4c8ca627-31c7-4b68-847d-baf5c3cc0db8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tsuid_24']/span/div/div/div[3]/div/div/div[2]/div/div/span</value>
      <webElementGuid>5b8ab1cb-fe01-42a6-8a04-12778041bd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::span[1]</value>
      <webElementGuid>c26e1fa8-1fda-456f-ab9b-fd97124237c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oxford Languages'])[1]/following::span[2]</value>
      <webElementGuid>95e6acd7-3c34-49b8-a285-93e6e8730df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tɛst'])[1]/preceding::span[1]</value>
      <webElementGuid>dbae5e20-3589-46b3-91bd-b07843371b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/span</value>
      <webElementGuid>32746fdf-52ee-44e1-96c9-94a56baf8b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'test' or . = 'test')]</value>
      <webElementGuid>a183129d-3c60-41a3-910b-6cd74c86a0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
