<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sale_attachment-woocommerce_thumbnail s_432ea2</name>
   <tag></tag>
   <elementGuidId>1284da97-988e-4def-9ca7-58ea2999ce52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div[2]/ul/li/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57a5ae7f-f123-4824-87a1-99703dfa3c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>eaeabcb7-8ddd-44cf-8fff-df20c5629146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>0b0a000f-04e2-4283-acba-55512d208849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg</value>
      <webElementGuid>6e7123f0-9d03-481d-ba9a-d20045c8e6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>e72b7ce4-a479-468d-aa8d-a362b5026cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg 300w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-150x150.jpg 150w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-768x768.jpg 768w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-675x675.jpg 675w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-323x323.jpg 323w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-440x440.jpg 440w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-600x600.jpg 600w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-100x100.jpg 100w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up.jpg 1000w</value>
      <webElementGuid>5d33b519-585c-425c-a7f9-744947b7cef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>5fd912ec-4a70-4a9d-a452-496918f6c479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;columns-3&quot;]/ul[@class=&quot;products columns-3&quot;]/li[@class=&quot;product type-product post-54 status-publish first instock product_cat-posters has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple&quot;]/div[@class=&quot;ellie-thumb-wrapper&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>f0911e2c-671a-4f5f-8a59-6b2b281d8751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/ul/li/div/a/img</value>
      <webElementGuid>641b9845-ef6f-4af4-93d3-48eba2ba76ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg')]</value>
      <webElementGuid>3292c483-99df-4d5c-a65e-abdac2fb7259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3fc41100-d548-463d-b927-71fd8e2d96bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg']</value>
      <webElementGuid>5133205f-cffd-4a38-9add-d6baa77b53ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
