<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sale_attachment-woocommerce_thumbnail s_432ea2</name>
   <tag></tag>
   <elementGuidId>15fc6097-e5f8-4503-b14d-3c09c9779d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div[2]/ul/li/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00cbcc89-f4d5-45c8-a656-9490fd7f77eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>82af9176-d647-40f7-bf4b-80afbafe3d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>f3e215ff-9060-49aa-a38f-5a0e495ad49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg</value>
      <webElementGuid>fca0235b-45fe-44ce-b3f7-12d71ad9a86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>eb4d7e43-bf5c-443f-bd6a-296d00e2587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg 300w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-150x150.jpg 150w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-768x768.jpg 768w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-675x675.jpg 675w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-323x323.jpg 323w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-440x440.jpg 440w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-600x600.jpg 600w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-100x100.jpg 100w, https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up.jpg 1000w</value>
      <webElementGuid>076b8033-6291-484e-97f4-52552fffb8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>16567f52-8737-428b-8fbb-62b34b3dd137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;columns-3&quot;]/ul[@class=&quot;products columns-3&quot;]/li[@class=&quot;product type-product post-54 status-publish first instock product_cat-posters has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple&quot;]/div[@class=&quot;ellie-thumb-wrapper&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>0ddba468-5987-4198-8f71-75c12e667291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/ul/li/div/a/img</value>
      <webElementGuid>4575b986-c360-41c7-b07c-1744a511b476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg')]</value>
      <webElementGuid>cfef8ea7-3641-452a-b074-3fb9a82c18cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8ef4b822-a396-42dd-8f2a-8fbbd5e884d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cms.demo.katalon.com/wp-content/uploads/2019/08/poster_2_up-300x300.jpg']</value>
      <webElementGuid>f7116b20-9e04-4264-9609-d37be1f8fb4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
